FROM debian:stable-slim

ENV DOMOTICZ_HOME=/opt/domoticz
ENV DOMOTICZ_URL="https://releases.domoticz.com/releases/release/domoticz_linux_armv7l.tgz"
ENV DOMOTICZ_FILENAME="domoticz.tgz"

RUN  apt-get update \
    && apt-get install -y wget libusb-dev libcurl3-gnutls libpython3-dev \
    && rm -rf /var/lib/apt/lists/* \
    && mkdir -p $DOMOTICZ_HOME/config \
    && cd $DOMOTICZ_HOME/../ \
    && wget -q -O ${DOMOTICZ_FILENAME} ${DOMOTICZ_URL} \
    && mkdir -p $DOMOTICZ_HOME/config && cd $DOMOTICZ_HOME && pwd && ls -al \
    && tar -xzf ../${DOMOTICZ_FILENAME}

CMD ["/opt/domoticz/domoticz", "-dbase", "/opt/domoticz/config/domoticz.db", "-log", "/opt/domoticz/log/domoticz.log", "-loglevel", "normal,status,error,debug"]
