version: "3"
services:
  domoticz:
    image: domoticz
    container_name: domoticz
    hostname: raspi-4b-1
    network_mode: "host"
    build:
      context: ./
      dockerfile: Dockerfile_domoticz
    volumes:
      - /opt/docker/domoticz/config:/opt/domoticz/config
      - /opt/docker/splunkforwarder/var/log/domoticz:/opt/domoticz/log
    ports:
      - 8080:8080
      - 6144:6144
      - 1443:1443
      - 9898:9898/udp
    restart: unless-stopped
  splunkforwarder:
    image: splunkforwarder
    container_name: splunkforwarder
    hostname: raspi-4b-1
    network_mode: "host"
    build:
      context: ./
      dockerfile: Dockerfile_splunkforwarder
    environment:
      - "SPLUNK_START_ARGS=--accept-license --answer-yes --no-prompt"
      - "SPLUNK_PASSWORD=changeme"
      - "SPLUNK_INDEXER_CONN=<splunk_indexer_host>:<splunk_indexer_port>"
    volumes:
      - /opt/docker/splunkforwarder/var/log:/opt/splunkforwarder/var/log
    ports:
      - 514:514/udp
    restart: unless-stopped
