FROM debian:stable-slim
ENV DOMOTICZ_HOME=/opt/domoticz
RUN  apt-get update \
  && apt-get install -y wget libusb-dev libcurl3-gnutls libpython3-dev \
  && rm -rf /var/lib/apt/lists/*
RUN mkdir -p $DOMOTICZ_HOME/config && \
    cd $DOMOTICZ_HOME/../ && \
    wget -q https://releases.domoticz.com/releases/release/domoticz_linux_x86_64.tgz
RUN mkdir -p $DOMOTICZ_HOME/config && cd $DOMOTICZ_HOME && pwd && ls -al && \
    tar -xzf ../domoticz_linux_x86_64.tgz
CMD ["/opt/domoticz/domoticz", "-dbase", "/opt/domoticz/config/domoticz.db", "-log", "/opt/domoticz/log/domoticz.log", "-loglevel", "normal,status,error,debug"]
